### ISSUE TITLE
lsdrv does not like nvme devices

### ISSUE THREAD

**Issue by JanCeuleers** [pturmel/lsdrv#10]
lsdrv errors out as follows when run on a machine containing an nvme device:

# lsdrv 
Traceback (most recent call last):
  File "/usr/bin/lsdrv", line 413, in <module>
    probe_block('/sys/block/'+x)
  File "/usr/bin/lsdrv", line 409, in probe_block
    probe_block(blkpath+'/'+part)
  File "/usr/bin/lsdrv", line 306, in probe_block
    blk.sizestr=sect2size(blk.size)
  File "/usr/bin/lsdrv", line 191, in sect2size
    return k2size(int(sectors)/2.0, fmt)
TypeError: int() argument must be a string or a number, not 'NoneType'

# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 119.2G  0 disk 
├─nvme0n1p5 259:3    0  11.2G  0 part [SWAP]
├─nvme0n1p1 259:1    0  74.5G  0 part /
└─nvme0n1p2 259:2    0     1K  0 part 

# ls -l /sys/dev/block/
total 0
lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:0 -> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1
lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:1 -> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p1
lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:2 -> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:3 -> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p5
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:0 -> ../../devices/virtual/block/loop0
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:1 -> ../../devices/virtual/block/loop1
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:2 -> ../../devices/virtual/block/loop2
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:3 -> ../../devices/virtual/block/loop3
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:4 -> ../../devices/virtual/block/loop4
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:5 -> ../../devices/virtual/block/loop5
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:6 -> ../../devices/virtual/block/loop6
lrwxrwxrwx 1 root root 0 Jun 24 10:05 7:7 -> ../../devices/virtual/block/loop7

# ls /sys/dev/block/259\:0/
alignment_offset  discard_alignment  integrity  nvme0n1p5  ro         trace
bdi               eui                mq         power      size       uevent
capability        ext_range          nsid       queue      slaves     wwid
dev               holders            nvme0n1p1  range      stat
device            inflight           nvme0n1p2  removable  subsystem

# cat /sys/dev/block/259\:0/size
250069680

**Comment by pturmel** [comment]
Hi Jan,

On 06/24/2018 04:15 AM, JanCeuleers wrote:
> lsdrv errors out as follows when run on a machine containing an nvme device:
> 
> 
>   lsdrv
> 
> Traceback (most recent call last):
> File "/usr/bin/lsdrv", line 413, in
> probe_block('/sys/block/'+x)
> File "/usr/bin/lsdrv", line 409, in probe_block
> probe_block(blkpath+'/'+part)
> File "/usr/bin/lsdrv", line 306, in probe_block
> blk.sizestr=sect2size(blk.size)
> File "/usr/bin/lsdrv", line 191, in sect2size
> return k2size(int(sectors)/2.0, fmt)
> TypeError: int() argument must be a string or a number, not 'NoneType'

This backtrace doesn't match the line numbers of the current version of
lsdrv.  Please update and reproduce.  But also...

[trim/]

>   ls -l /sys/dev/block/
> 
> total 0
> lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:0 ->
> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1
> lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:1 ->
> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p1
> lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:2 ->
> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
> lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:3 ->>
../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p5

[trim/]

>   cat /sys/dev/block/259:0/size
> 
> 250069680

Please also show the size entries for 259:1, :2, and :3.

The "None" suggests the partitions' size files aren't there.

Phil

**Comment by JanCeuleers** [comment]
On 24/06/18 20:23, Philip J. Turmel wrote:
> This backtrace doesn't match the line numbers of the current version of
> lsdrv. Please update and reproduce. But also...
>

Fair enough. Here is the backtrace with current head:

Traceback (most recent call last):
  File "./lsdrv", line 420, in <module>
    probe_block('/sys/block/'+x)
  File "./lsdrv", line 416, in probe_block
    probe_block(blkpath+'/'+part)
  File "./lsdrv", line 313, in probe_block
    blk.sizestr=sect2size(blk.size)
  File "./lsdrv", line 191, in sect2size
    return k2size(int(sectors)/2.0, fmt)
TypeError: int() argument must be a string or a number, not 'NoneType'

> > ls -l /sys/dev/block/
> >
> > total 0
> > lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:0 ->
> > ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1
> > lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:1 ->
> >
> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p1
> > lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:2 ->
> >
> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
> > lrwxrwxrwx 1 root root 0 Jun 24 10:05 259:3 ->>
> ../../devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p5
>
> [trim/]
>
> > cat /sys/dev/block/259:0/size
> >
> > 250069680
>
> Please also show the size entries for 259:1, :2, and :3.
>
> The "None" suggests the partitions' size files aren't there.

# ls -l /sys/dev/block/259:?/
/sys/dev/block/259:0/:
total 0
-r--r--r-- 1 root root 4096 Jun 24 10:07 alignment_offset
lrwxrwxrwx 1 root root    0 Jun 24 10:07 bdi ->
../../../../../../virtual/bdi/259:0
-r--r--r-- 1 root root 4096 Jun 24 10:07 capability
-r--r--r-- 1 root root 4096 Jun 24 10:07 dev
lrwxrwxrwx 1 root root    0 Jun 24 10:07 device -> ../../nvme0
-r--r--r-- 1 root root 4096 Jun 24 10:07 discard_alignment
-r--r--r-- 1 root root 4096 Jun 24 10:07 eui
-r--r--r-- 1 root root 4096 Jun 24 10:07 ext_range
drwxr-xr-x 2 root root    0 Jun 24 10:07 holders
-r--r--r-- 1 root root 4096 Jun 24 10:07 inflight
drwxr-xr-x 2 root root    0 Jun 24 10:07 integrity
drwxr-xr-x 6 root root    0 Jun 24 10:07 mq
-r--r--r-- 1 root root 4096 Jun 24 10:07 nsid
drwxr-xr-x 5 root root    0 Jun 24 10:07 nvme0n1p1
drwxr-xr-x 5 root root    0 Jun 24 10:07 nvme0n1p2
drwxr-xr-x 5 root root    0 Jun 24 10:07 nvme0n1p5
drwxr-xr-x 2 root root    0 Jun 24 10:07 power
drwxr-xr-x 2 root root    0 Jun 24 10:07 queue
-r--r--r-- 1 root root 4096 Jun 24 10:07 range
-r--r--r-- 1 root root 4096 Jun 24 10:07 removable
-r--r--r-- 1 root root 4096 Jun 24 10:07 ro
-r--r--r-- 1 root root 4096 Jun 24 10:07 size
drwxr-xr-x 2 root root    0 Jun 24 10:07 slaves
-r--r--r-- 1 root root 4096 Jun 24 10:07 stat
lrwxrwxrwx 1 root root    0 Jun 24 10:07 subsystem ->
../../../../../../../class/block
drwxr-xr-x 2 root root    0 Jun 24 10:07 trace
-rw-r--r-- 1 root root 4096 Jun 24 10:07 uevent
-r--r--r-- 1 root root 4096 Jun 24 10:07 wwid

/sys/dev/block/259:1/:
total 0
-r--r--r-- 1 root root 4096 Jun 25 17:45 alignment_offset
-r--r--r-- 1 root root 4096 Jun 25 17:45 dev
-r--r--r-- 1 root root 4096 Jun 25 17:45 discard_alignment
drwxr-xr-x 2 root root    0 Jun 25 17:45 holders
-r--r--r-- 1 root root 4096 Jun 25 17:45 inflight
-r--r--r-- 1 root root 4096 Jun 25 17:45 partition
drwxr-xr-x 2 root root    0 Jun 25 17:45 power
-r--r--r-- 1 root root 4096 Jun 25 17:45 ro
-r--r--r-- 1 root root 4096 Jun 25 17:45 size
-r--r--r-- 1 root root 4096 Jun 25 17:45 start
-r--r--r-- 1 root root 4096 Jun 25 17:45 stat
lrwxrwxrwx 1 root root    0 Jun 25 17:45 subsystem ->
../../../../../../../../class/block
drwxr-xr-x 2 root root    0 Jun 25 17:45 trace
-rw-r--r-- 1 root root 4096 Jun 25 17:45 uevent

/sys/dev/block/259:2/:
total 0
-r--r--r-- 1 root root 4096 Jun 25 17:45 alignment_offset
-r--r--r-- 1 root root 4096 Jun 25 17:45 dev
-r--r--r-- 1 root root 4096 Jun 25 17:45 discard_alignment
drwxr-xr-x 2 root root    0 Jun 25 17:45 holders
-r--r--r-- 1 root root 4096 Jun 25 17:45 inflight
-r--r--r-- 1 root root 4096 Jun 25 17:45 partition
drwxr-xr-x 2 root root    0 Jun 25 17:45 power
-r--r--r-- 1 root root 4096 Jun 25 17:45 ro
-r--r--r-- 1 root root 4096 Jun 25 17:45 size
-r--r--r-- 1 root root 4096 Jun 25 17:45 start
-r--r--r-- 1 root root 4096 Jun 25 17:45 stat
lrwxrwxrwx 1 root root    0 Jun 25 17:45 subsystem ->
../../../../../../../../class/block
drwxr-xr-x 2 root root    0 Jun 25 17:45 trace
-rw-r--r-- 1 root root 4096 Jun 25 17:45 uevent

/sys/dev/block/259:3/:
total 0
-r--r--r-- 1 root root 4096 Jun 25 17:45 alignment_offset
-r--r--r-- 1 root root 4096 Jun 25 17:45 dev
-r--r--r-- 1 root root 4096 Jun 25 17:45 discard_alignment
drwxr-xr-x 2 root root    0 Jun 25 17:45 holders
-r--r--r-- 1 root root 4096 Jun 25 17:45 inflight
-r--r--r-- 1 root root 4096 Jun 25 17:45 partition
drwxr-xr-x 2 root root    0 Jun 25 17:45 power
-r--r--r-- 1 root root 4096 Jun 25 17:45 ro
-r--r--r-- 1 root root 4096 Jun 25 17:45 size
-r--r--r-- 1 root root 4096 Jun 25 17:45 start
-r--r--r-- 1 root root 4096 Jun 25 17:45 stat
lrwxrwxrwx 1 root root    0 Jun 25 17:45 subsystem ->
../../../../../../../../class/block
drwxr-xr-x 2 root root    0 Jun 25 17:45 trace
-rw-r--r-- 1 root root 4096 Jun 25 17:45 uevent

# cat /sys/dev/block/259:?/size
250069680
156248064
2
23435264

**Comment by JanCeuleers** [comment]
I think the problem may be that the size file in /sys/block for an nvme device is not zero-terminated:

```
root@dracor:~# cat /sys/block/nvme0n1/size 
488397168
root@dracor:~# hexdump /sys/block/nvme0n1/size 
0000000 3834 3338 3739 3631 0a38               
000000a
root@dracor:~# cat /sys/block/sda/size
7814053888
root@dracor:~# hexdump /sys/block/sda/size 
0000000 3837 3431 3530 3833 3838 000a          
000000b

```

**Comment by romanrm** [comment]
Same here. Should be at least a way to tell it to exclude the problematic device from listing. As is, it even fails with "--help"!

> $ sudo ./lsdrv --help
> Traceback (most recent call last):
>   File "./lsdrv", line 420, in <module>
>     probe_block('/sys/block/'+x)
>   File "./lsdrv", line 416, in probe_block
>     probe_block(blkpath+'/'+part)
>   File "./lsdrv", line 313, in probe_block
>     blk.sizestr=sect2size(blk.size)
>   File "./lsdrv", line 191, in sect2size
>     return k2size(int(sectors)/2.0, fmt)
> TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by pturmel** [comment]
Pushed a fix for the None failing to evaluate in sect2size().  I'm not
sure how the string termination matters -- I'm just using readline() to
grab that value (Struct class line 46).

I will have to experiment with that.

**Comment by JanCeuleers** [comment]
That's helped:

`
PCI [nvme] 03:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd Device a804
└nvme nvme0 SAMSUNG MZVLW128HEGR-00000               {S33WNX0JC00270}
 └nvme0n1 119.24g [259:0] Partitioned (dos)
  ├nvme0n1p1 74.50g [259:1] ext4 {b81dbba9-f908-4bf5-9654-6470824d25b8}
  │└Mounted as /dev/nvme0n1p1 @ /
  ├nvme0n1p2 1.00k [259:2] Partitioned (dos)
  └nvme0n1p5 11.17g [259:3] swap {e9833695-aa01-44e4-a94a-67d89e7f33b5}
USB [usb-storage] Bus 001 Device 002: ID 1c6b:a223 Philips & Lite-ON Digital Solutions Corporation  {06 638323402045}
└scsi 0:0:0:0 Slimtype eUAU108  5A     
 └sr0 1.00g [11:0] Empty/Unknown
PCI [ahci] 00:17.0 SATA controller: Intel Corporation Device a282
└scsi 4:0:0:0 ATA      Samsung SSD 860  {S3Z9NB0K520002M}
 └sda 931.51g [8:0] Partitioned (gpt)
  └sda1 833.86g [8:1] ext4 {aee3509c-e82c-4e09-aa38-2a23d3a28201}
   └Mounted as /dev/sda1 @ /mnt/disk6
Other Block Devices
├loop0 0.00k [7:0] Empty/Unknown
├loop1 0.00k [7:1] Empty/Unknown
├loop2 0.00k [7:2] Empty/Unknown
├loop3 0.00k [7:3] Empty/Unknown
├loop4 0.00k [7:4] Empty/Unknown
├loop5 0.00k [7:5] Empty/Unknown
├loop6 0.00k [7:6] Empty/Unknown
└loop7 0.00k [7:7] Empty/Unknown

`

Thanks much
